apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: jenkins-restored-volume
  resources:
    requests:
      storage: MATCH PV VOLUME SIZE HERE
