package:
  deploy:
    set:
      REGISTRY_PVC_ENABLED: "false"
      REGISTRY_SERVICE_ACCOUNT_NAME: "docker-registry-sa"
      REGISTRY_CREATE_SERVICE_ACCOUNT: "true"
      REGISTRY_SERVICE_ACCOUNT_ANNOTATIONS: "eks.amazonaws.com/role-arn: arn:aws-us-gov:iam::233421754748:role/du-dev-swf-zarf-registry-irsa-role-1a60"
      REGISTRY_EXTRA_ENVS: |
        - name: REGISTRY_STORAGE
          value: s3
        - name: REGISTRY_STORAGE_S3_REGION
          value: "us-gov-west-1"
        - name: REGISTRY_STORAGE_S3_BUCKET
          value: "du-dev-swf-zarf-registry-1a602024040420580287370000000e"
      REGISTRY_HPA_AUTO_SIZE: "true"
      REGISTRY_AFFINITY_CUSTOM: |
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - docker-registry
                topologyKey: kubernetes.io/hostname
      REGISTRY_TOLERATIONS: |
        - effect: NoSchedule
          key: dedicated
          operator: Exists