apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artifactory-pvc
  namespace: artifactory
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: artifactory-restored-volume
  resources:
    requests:
      storage: 50Gi
