apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: gitlab-rails-backup
  namespace: velero
spec:
  schedule: "0 0 * * *"
  template:
    includeClusterResources: false
    includedNamespaces:
      - gitlab
    includedResources:
      - secrets
    labelSelector:
      matchLabels:
        app: gitlab
        heritage: Helm
        release: gitlab
    ttl: 240h
  skipImmediately: false
