tasks:
  - name: zarf-create
    description: "Creates the swf package"
    actions:
      - cmd: uds zarf package create -a amd64 ./zarf/swf-deps-aws --confirm --no-progress

  - name: zarf-deploy
    description: "Creates the swf package"
    actions:
      - cmd: uds zarf package create -a amd64 ./zarf/swf-deps-aws --confirm --no-progress

  - name: bundle-create
    description: "Creates the swf bundle"
    actions:
      - cmd: uds create bundles/swf/ -a amd64 --confirm --no-progress

  - name: bundle-deploy
    description: "Deploys the swf bundle"
    actions:
      - cmd: uds deploy bundles/swf/ --confirm --no-progress

  - name: uds-config
    actions:
      - description: "Moves the uds-config.yaml to an appropriate spot"
        cmd: mv ./iac/swf/uds-config.yaml ./bundles/swf/
