apiVersion: v1
kind: ServiceAccount
metadata:
  name: watch-recycle-sa
  namespace: pepr-system
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: pepr-system
  name: watch-recycle-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete","list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watch-recycle-binding
  namespace: pepr-system
subjects:
- kind: ServiceAccount
  name: watch-recycle-sa
roleRef:
  kind: Role
  name: watch-recycle-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-deleter-job
  namespace: pepr-system
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: watch-recycle-sa
          restartPolicy: OnFailure
          containers:
          - name: kubectl-container
            image: registry1.dso.mil/ironbank/chainguard-dev/wolfi/kubectl:stable
            args:
              - delete
              - pods
              - --force
              - --grace-period=0
              - -n
              - pepr-system
              - -l
              - pepr.dev/controller=watcher
