apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitaly-volume
  labels:
    app: gitaly
    restored: yup
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-06ca1b0b529382d0d
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  volumeMode: Filesystem
