apiVersion: v1
data:
  password: < initial root password >
kind: Secret
metadata:
  creationTimestamp: "2024-03-25T18:58:46Z"
  labels:
    app: gitlab
    chart: gitlab-7.9.2-bb.0
    heritage: Helm
    release: gitlab
  name: gitlab-gitlab-initial-root-password
  namespace: gitlab
  resourceVersion: "2015819"
  uid: d955a9f7-2d30-4783-ad72-87672f2b562c
type: Opaque
