apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-restored-shared-volume
spec:
  capacity:
    storage: MATCH PVC VOLUME SIZE HERE
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs
  csi:
    driver: efs.csi.aws.com
    volumeHandle: [FileSystemId]::[AccessPointId]
