apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-shared-home-pvc
  namespace: jira
spec:
  accessModes:
    - ReadWriteMany
  volumeName: jira-restored-shared-volume
  resources:
    requests:
      storage: MATCH PV VOLUME SIZE HERE
  storageClassName: efs
