apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
  labels:
    app: jenkins
    restored: yup
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-093116130d780e5e4
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3
  volumeMode: Filesystem
